name: Cloudflare Tunnel
version: 1.6.1
slug: cloudflare_tunnel
description: Cloudflare Tunnel for Home Assistant
url: https://github.com/w35l3y/hassio-addons/tree/main/cloudflare_tunnel
codenotary: www.wesley@gmail.com
ingress: false
init: false
watchdog: http://[HOST]:41705/healthcheck
webui: http://[HOST]:[PORT:41705]/metrics
apparmor: true
panel_icon: mdi:tunnel
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - config:rw
  - ssl:ro
startup: services
boot: auto
ports:
  41705/tcp:
options:
  tunnel: homeassistant
  credentials-file: "/data/tunnel.json"
  protocol: auto
  origincert: "/data/cert.pem"
  log_level: info
  loglevel: info
  transport-loglevel: warn
  ingress:
    - hostname: ""
      service: http://homeassistant:8123
    - service: http_status:404
  originRequest: {}
  warp-routing:
    enabled: false
  metrics: 0.0.0.0:41705
  metrics-update-freq: 5s
  grace-period: 30s
  retries: 5
  no-autoupdate: true
schema:
  tunnel: str?
  credentials-file: str?
  protocol: list(auto|http2|h2mux|quic)
  origincert: str?
  logfile: str?
  log_level: list(notset|debug|info|warn|warning|error|fatal|critical)
  loglevel: list(trace|debug|info|warn|error|fatal|panic)?
  transport-loglevel: list(trace|debug|info|warn|error|fatal|panic)?
  url: str?
  ingress:
    - hostname: str?
      path: str?
      service: str?
  originRequest:
    connectTimeout: str?
    tlsTimeout: str?
    tcpKeepAlive: str?
    noHappyEyeballs: bool?
    keepAliveConnections: int(0,)?
    keepAliveTimeout: str?
    httpHostHeader: str?
    originServerName: str?
    caPool: str?
    noTLSVerify: bool?
    disableChunkedEncoding: bool?
    proxyAddress: str?
    proxyPort: port?
    proxyType: str?
  warp-routing:
    enabled: bool?
  metrics: str?
  metrics-update-freq: str?
  grace-period: str?
  retries: int(0,)?
  no-autoupdate: bool?
  autoupdate-freq: str?
  tag: str?
  pidfile: str?
  region: str?
